# Generated by Django 4.2.6 on 2023-12-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='confirm_password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
