# Generated by Django 4.2.6 on 2023-12-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0002_person_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user_type',
            field=models.CharField(default='patient', max_length=10),
        ),
    ]
