# Generated by Django 4.2.6 on 2023-12-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0003_person_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user_type',
            field=models.CharField(default='Patient', max_length=10),
        ),
    ]
