# Generated by Django 4.2.6 on 2023-12-07 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authusers', '0005_person_person_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='person_id',
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
