# Generated by Django 4.2.6 on 2023-12-07 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0006_remove_person_person_id_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
    ]
